---
title: "Untitled"
author: "Bryan Ding"
date: "5/31/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Vegan

```{r}
set.seed(2)
library(factoextra)
library(cluster)

vegan <- read.csv("vegan2d.csv")
rownames(vegan) <- vegan[,3]
vegan <- vegan[,-3]

fviz_nbclust(vegan, kmeans, method = "wss")
km1 <- kmeans(vegan, centers = 7, nstart = 25)

cooking_process1 <- vegan[which(km1$cluster == 1),]
prep_process1<- vegan[which(km1$cluster == 2),]
seasoning1 <- vegan[which(km1$cluster == 3),]
general_heating1 <- vegan[which(km1$cluster == 4),]
ingredients1 <- vegan[which(km1$cluster == 5),]
utensil_use1 <- vegan[which(km1$cluster == 6),]
boiling1 <- vegan[which(km1$cluster == 7),]

fviz_cluster(km1, data = vegan, axes = c(10,50), main = "Vegan diet", labelsize = 8)
```

# Dairy Free
```{r}
set.seed(2)
dairy <- read.csv("dairyFree2d.csv")
rownames(dairy) <- dairy[,3]
dairy <- dairy[,-3]

fviz_nbclust(dairy, kmeans, method = "wss")
km2 <- kmeans(dairy, centers = 7, nstart = 25)


cooking_process2 <- dairy[which(km2$cluster == 1),]
ingredients2 <- dairy[which(km2$cluster == 2),]
general_heating2 <- dairy[which(km2$cluster == 3),]
boiling2 <- dairy[which(km2$cluster == 4),]
utensil_use2 <- dairy[which(km2$cluster == 5),]
prep_process2 <- dairy[which(km2$cluster == 6),]
seasoning2 <- dairy[which(km2$cluster == 7),]



fviz_cluster(km2, data = dairy, axes = c(10,50), main = "dairy diet", labelsize = 8)
```

# Gluten Free

```{r}
set.seed(2)
gluten <- read.csv("glutenFree2d.csv")
rownames(gluten) <- gluten[,3]
gluten <- gluten[,-3]

fviz_nbclust(gluten, kmeans, method = "wss")
km3 <- kmeans(gluten, centers = 7, nstart = 25)
km3

ingredients3 <- gluten[which(km3$cluster == 1),]
boiling3 <- gluten[which(km3$cluster == 2),]
cooking_process3 <- gluten[which(km3$cluster == 3),]
prep_process3 <- gluten[which(km3$cluster == 4),]
utensil_use3 <- gluten[which(km3$cluster == 5),]
seasoning3 <- gluten[which(km3$cluster == 6),]
general_heating3 <- gluten[which(km3$cluster == 7),]


fviz_cluster(km3, data = gluten, axes = c(10,50), main = "gluten diet", labelsize = 8)
```


# Regular
```{r}
set.seed(1)
reg <- read.csv("reg2d.csv")
rownames(reg) <- reg[,3]
reg <- reg[,-3]

fviz_nbclust(reg, kmeans, method = "wss")
km4 <- kmeans(reg, centers = 5, nstart = 25)

prep_process4 <- reg[which(km4$cluster == 1),]
baking4 <- reg[which(km4$cluster == 2),]
ingredients4 <- reg[which(km4$cluster == 3),]
cooking_process4 <- reg[which(km4$cluster == 4),]
utensil_use4 <- reg[which(km4$cluster == 5),]


fviz_cluster(km4, data = reg, axes = c(10,50), main = "reg diet", labelsize = 8)
```

